import socket


def get_ip_address():
    try:
        # Create a socket connection
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        # Connect to an external server (Google's DNS server in this case)
        s.connect(("8.8.8.8", 80))
        # Get the local IP address
        ip_address = s.getsockname()[0]
    finally:
        s.close()

    return ip_address


students = [
    {
        "S.NO": 1,
        "username": "23BECSE064",
        "password": "23BECSE064",
        "first_name": "HARIHARAN",
        "last_name": "A",
        "phone": "6379077471",
        "email": "23BECSE064@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 2,
        "username": "23BECSE065",
        "password": "23BECSE065",
        "first_name": "HARIHARAN",
        "last_name": "S",
        "phone": "7558142358",
        "email": "23BECSE065@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 3,
        "username": "23BECSE066",
        "password": "23BECSE066",
        "first_name": "HARISH",
        "last_name": "B",
        "phone": "9342193839",
        "email": "23BECSE066@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 4,
        "username": "23BECSE067",
        "password": "23BECSE067",
        "first_name": "HARISH",
        "last_name": "K M",
        "phone": "9025770059",
        "email": "23BECSE067@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 5,
        "username": "23BECSE068",
        "password": "23BECSE068",
        "first_name": "HARISHRAGAVAN",
        "last_name": "S",
        "phone": "8870031939",
        "email": "23BECSE068@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 6,
        "username": "23BECSE069",
        "password": "23BECSE069",
        "first_name": "HARISHMITHA",
        "last_name": "A",
        "phone": "8754818035",
        "email": "23BECSE069@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 7,
        "username": "23BECSE070",
        "password": "23BECSE070",
        "first_name": "HARISHRAM",
        "last_name": "RAJENDRAN",
        "phone": "9952528866",
        "email": "23BECSE070@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 8,
        "username": "23BECSE071",
        "password": "23BECSE071",
        "first_name": "HARISUDHAN",
        "last_name": "T",
        "phone": "9361392797",
        "email": "23BECSE071@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 9,
        "username": "23BECSE072",
        "password": "23BECSE072",
        "first_name": "HARISUDHIR",
        "last_name": "N G",
        "phone": "9360686546",
        "email": "23BECSE072@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 10,
        "username": "23BECSE073",
        "password": "23BECSE073",
        "first_name": "HEMADARINI",
        "last_name": "T",
        "phone": "8778994654",
        "email": "23BECSE073@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 11,
        "username": "23BECSE074",
        "password": "23BECSE074",
        "first_name": "HIROSH",
        "last_name": "S",
        "phone": "9976756990",
        "email": "23BECSE074@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 12,
        "username": "23BECSE075",
        "password": "23BECSE075",
        "first_name": "INDHUMATHI",
        "last_name": "G",
        "phone": "9345163917",
        "email": "23BECSE075@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 13,
        "username": "23BECSE076",
        "password": "23BECSE076",
        "first_name": "INFANT",
        "last_name": "FLASHZIT F",
        "phone": "7358889393",
        "email": "23BECSE076@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 14,
        "username": "23BECSE077",
        "password": "23BECSE077",
        "first_name": "INIKA",
        "last_name": "G",
        "phone": "8428014525",
        "email": "23BECSE077@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 15,
        "username": "23BECSE078",
        "password": "23BECSE078",
        "first_name": "JAYAKUMAR",
        "last_name": "K",
        "phone": "9363298592",
        "email": "23BECSE078@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 16,
        "username": "23BECSE079",
        "password": "23BECSE079",
        "first_name": "JAYARAJ",
        "last_name": "S",
        "phone": "7010002510",
        "email": "23BECSE079@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 17,
        "username": "23BECSE080",
        "password": "23BECSE080",
        "first_name": "JAYASURYA",
        "last_name": "J",
        "phone": "8825778011",
        "email": "23BECSE080@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 18,
        "username": "23BECSE081",
        "password": "23BECSE081",
        "first_name": "JAYAVEL",
        "last_name": "RAJAA V R",
        "phone": "6369546617",
        "email": "23BECSE081@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 19,
        "username": "23BECSE082",
        "password": "23BECSE082",
        "first_name": "JEBASIMSON",
        "last_name": "S",
        "phone": "8072580279",
        "email": "23BECSE082@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 20,
        "username": "23BECSE083",
        "password": "23BECSE083",
        "first_name": "JEBIN",
        "last_name": "AKASH RAJA A",
        "phone": "7904580624",
        "email": "23BECSE083@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 21,
        "username": "23BECSE084",
        "password": "23BECSE084",
        "first_name": "JEEVAPRIYAN",
        "last_name": "G",
        "phone": "8344698479",
        "email": "23BECSE084@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 22,
        "username": "23BECSE085",
        "password": "23BECSE085",
        "first_name": "JEEVENDRAN",
        "last_name": "M",
        "phone": "9087523540",
        "email": "23BECSE085@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 23,
        "username": "23BECSE086",
        "password": "23BECSE086",
        "first_name": "JESUNATH",
        "last_name": "N",
        "phone": "9888794075",
        "email": "23BECSE086@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 24,
        "username": "23BECSE087",
        "password": "23BECSE087",
        "first_name": "JOSHI",
        "last_name": "J",
        "phone": "7995923431",
        "email": "23BECSE087@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 25,
        "username": "23BECSE088",
        "password": "23BECSE088",
        "first_name": "JYOTHI",
        "last_name": "R",
        "phone": "7667534700",
        "email": "23BECSE088@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 26,
        "username": "23BECSE089",
        "password": "23BECSE089",
        "first_name": "KAVITHA",
        "last_name": "G",
        "phone": "9384358969",
        "email": "23BECSE089@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 27,
        "username": "23BECSE090",
        "password": "23BECSE090",
        "first_name": "KARTHIK",
        "last_name": "K",
        "phone": "9942091688",
        "email": "23BECSE090@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 28,
        "username": "23BECSE091",
        "password": "23BECSE091",
        "first_name": "KARTHIK",
        "last_name": "M",
        "phone": "9372160574",
        "email": "23BECSE091@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 29,
        "username": "23BECSE092",
        "password": "23BECSE092",
        "first_name": "KARTHIKESH",
        "last_name": "S",
        "phone": "9585593375",
        "email": "23BECSE092@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 30,
        "username": "23BECSE093",
        "password": "23BECSE093",
        "first_name": "KAVIN",
        "last_name": "R",
        "phone": "9629110302",
        "email": "23BECSE093@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 31,
        "username": "23BECSE094",
        "password": "23BECSE094",
        "first_name": "KAVIN",
        "last_name": "S",
        "phone": "8608220507",
        "email": "23BECSE094@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 32,
        "username": "23BECSE095",
        "password": "23BECSE095",
        "first_name": "KAVIN",
        "last_name": "P",
        "phone": "9500126573",
        "email": "23BECSE095@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 33,
        "username": "23BECSE096",
        "password": "23BECSE096",
        "first_name": "KAVIN",
        "last_name": "R",
        "phone": "9600394811",
        "email": "23BECSE096@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 34,
        "username": "23BECSE097",
        "password": "23BECSE097",
        "first_name": "KEERTHANA",
        "last_name": "S",
        "phone": "9842346150",
        "email": "23BECSE097@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 35,
        "username": "23BECSE098",
        "password": "23BECSE098",
        "first_name": "KIRUBA",
        "last_name": "T",
        "phone": "7639384501",
        "email": "23BECSE098@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 36,
        "username": "23BECSE099",
        "password": "23BECSE099",
        "first_name": "LAKSHMI",
        "last_name": "V",
        "phone": "8939405872",
        "email": "23BECSE099@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 37,
        "username": "23BECSE100",
        "password": "23BECSE100",
        "first_name": "LAKSHMI PRIYA",
        "last_name": "S",
        "phone": "9444062950",
        "email": "23BECSE100@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 38,
        "username": "23BECSE101",
        "password": "23BECSE101",
        "first_name": "LAVANYA",
        "last_name": "K",
        "phone": "9626181953",
        "email": "23BECSE101@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 39,
        "username": "23BECSE102",
        "password": "23BECSE102",
        "first_name": "LAVANYA",
        "last_name": "P",
        "phone": "9884197133",
        "email": "23BECSE102@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 40,
        "username": "23BECSE103",
        "password": "23BECSE103",
        "first_name": "MANJULA",
        "last_name": "P",
        "phone": "9087325529",
        "email": "23BECSE103@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 41,
        "username": "23BECSE104",
        "password": "23BECSE104",
        "first_name": "MAYURI",
        "last_name": "V",
        "phone": "9758879242",
        "email": "23BECSE104@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 42,
        "username": "23BECSE105",
        "password": "23BECSE105",
        "first_name": "MEERA",
        "last_name": "K",
        "phone": "9618074229",
        "email": "23BECSE105@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 43,
        "username": "23BECSE106",
        "password": "23BECSE106",
        "first_name": "MITHRA",
        "last_name": "V",
        "phone": "9350324551",
        "email": "23BECSE106@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 44,
        "username": "23BECSE107",
        "password": "23BECSE107",
        "first_name": "MOGANRAJ",
        "last_name": "P",
        "phone": "9872341242",
        "email": "23BECSE107@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 45,
        "username": "23BECSE108",
        "password": "23BECSE108",
        "first_name": "MOHAN",
        "last_name": "S",
        "phone": "8930483939",
        "email": "23BECSE108@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 46,
        "username": "23BECSE109",
        "password": "23BECSE109",
        "first_name": "MURUGAN",
        "last_name": "M",
        "phone": "9342384536",
        "email": "23BECSE109@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 47,
        "username": "23BECSE110",
        "password": "23BECSE110",
        "first_name": "MURUGESAN",
        "last_name": "S",
        "phone": "9376123456",
        "email": "23BECSE110@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 48,
        "username": "23BECSE111",
        "password": "23BECSE111",
        "first_name": "MUTHU",
        "last_name": "V",
        "phone": "9600872756",
        "email": "23BECSE111@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 49,
        "username": "23BECSE112",
        "password": "23BECSE112",
        "first_name": "NAVEEN",
        "last_name": "K",
        "phone": "9342483907",
        "email": "23BECSE112@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 50,
        "username": "23BECSE113",
        "password": "23BECSE113",
        "first_name": "NANDINI",
        "last_name": "P",
        "phone": "8772397467",
        "email": "23BECSE113@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 51,
        "username": "23BECSE114",
        "password": "23BECSE114",
        "first_name": "NAVANEETH",
        "last_name": "K",
        "phone": "9442812914",
        "email": "23BECSE114@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 52,
        "username": "23BECSE115",
        "password": "23BECSE115",
        "first_name": "NITHYA",
        "last_name": "K",
        "phone": "9894964242",
        "email": "23BECSE115@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 53,
        "username": "23BECSE116",
        "password": "23BECSE116",
        "first_name": "OMAN",
        "last_name": "P",
        "phone": "8779445506",
        "email": "23BECSE116@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 54,
        "username": "23BECSE117",
        "password": "23BECSE117",
        "first_name": "PALANI",
        "last_name": "S",
        "phone": "9227338495",
        "email": "23BECSE117@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 55,
        "username": "23BECSE118",
        "password": "23BECSE118",
        "first_name": "PRIYA",
        "last_name": "S",
        "phone": "9888322484",
        "email": "23BECSE118@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 56,
        "username": "23BECSE119",
        "password": "23BECSE119",
        "first_name": "PRAVEEN",
        "last_name": "S",
        "phone": "9683941762",
        "email": "23BECSE119@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 57,
        "username": "23BECSE120",
        "password": "23BECSE120",
        "first_name": "SANGEETHA",
        "last_name": "R",
        "phone": "8778236453",
        "email": "23BECSE120@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 58,
        "username": "23BECSE121",
        "password": "23BECSE121",
        "first_name": "SATHIYAMOORTHY",
        "last_name": "M",
        "phone": "9000807317",
        "email": "23BECSE121@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 59,
        "username": "23BECSE122",
        "password": "23BECSE122",
        "first_name": "SELVA",
        "last_name": "K",
        "phone": "9578126752",
        "email": "23BECSE122@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 60,
        "username": "23BECSE123",
        "password": "23BECSE123",
        "first_name": "SILVER",
        "last_name": "V",
        "phone": "9627427317",
        "email": "23BECSE123@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 61,
        "username": "23BECSE124",
        "password": "23BECSE124",
        "first_name": "SINDHU",
        "last_name": "P",
        "phone": "9156742896",
        "email": "23BECSE124@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 62,
        "username": "23BECSE125",
        "password": "23BECSE125",
        "first_name": "SIRISHA",
        "last_name": "S",
        "phone": "9885512757",
        "email": "23BECSE125@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 63,
        "username": "23BECSE126",
        "password": "23BECSE126",
        "first_name": "SOFIA",
        "last_name": "M",
        "phone": "9000304672",
        "email": "23BECSE126@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
    {
        "S.NO": 64,
        "username": "23BECSE127",
        "password": "23BECSE127",
        "first_name": "SREEJAYAM",
        "last_name": "K",
        "phone": "9043531166",
        "email": "23BECSE127@kahedu.edu.in",
        "REMARKS": "",
        "department":1,
        "program":1,
        "sem": 3,
        "batch": 2,
    },
]
